### ISSUE TITLE
htmlmin conflict with django-htmlmin

### ISSUE THREAD

**Issue by tigerfoot** [ioda-net/geo-infra#22]
Unfortunately for us, django-htmlmin and htmlmin python package conflicts, they both use some common place in filesystem (at least under openSUSE)

```
File /usr/lib/python3.5/site-packages/htmlmin/__init__.py
  from install of
     python3-django-htmlmin-0.9.1-3.1.noarch (bfdlp3)
  conflicts with file from install of
     python3-htmlmin-0.1.10-3.2.noarch (dlp3)

File /usr/lib/python3.5/site-packages/htmlmin/__pycache__/__init__.cpython-35.pyc
  from install of
     python3-django-htmlmin-0.9.1-3.1.noarch (bfdlp3)
  conflicts with file from install of
     python3-htmlmin-0.1.10-3.2.noarch (dlp3)

File /usr/lib/python3.5/site-packages/htmlmin/__pycache__/middleware.cpython-35.pyc
  from install of
     python3-django-htmlmin-0.9.1-3.1.noarch (bfdlp3)
  conflicts with file from install of
     python3-htmlmin-0.1.10-3.2.noarch (dlp3)

File /usr/lib/python3.5/site-packages/htmlmin/middleware.py
  from install of
     python3-django-htmlmin-0.9.1-3.1.noarch (bfdlp3)
  conflicts with file from install of
     python3-htmlmin-0.1.10-3.2.noarch (dlp3)
```

At system level the newer pgAdmin4 needs django-htmlmin 

Question : should we move our depency to django-htmlmin, or we can handle both by some switches and try catch ?

Error appearing with django-htmlmin

```
***** PROCESSING: geoportalxyz *****
Updating test configuration
Traceback (most recent call last):
  File "./scripts/render.py", line 263, in <module>
    main(args)
  File "./scripts/render.py", line 94, in main
    'partials': _get_partials(front_dir, config)
  File "./scripts/render.py", line 195, in _get_partials
    partial_content = htmlmin.minify(
AttributeError: module 'htmlmin' has no attribute 'minify'
```

@Jenselme you're feedback is welcome :-)

**Comment by Jenselme** [comment]
If both package rely on the same name, you cannot make them cohabitate: things will collide and prevent either package to work.

htmlmin has more features than dj-htmlmin: we use `remove_optional_attribute_quotes=False` which doesn't seem to have an equivalent in dj-htmlmin. Swisstopo relies on htmlmin with this option. I fear that if we turn it off or use something that doesn't support it we introduce subtle bugs with angular.

I see 4 solutions:
- Use venvs
- Switch to dj-htmlmin and hope nothing bad will happen with the front (I'll have problems at system level since python-htmlmin is an offical package in fedora)
- Ask pg-admin4 to use htmlmin
- Patch pg-admin4 to use htmlmin (shouldn't be too hard)

**Comment by tigerfoot** [comment]
Well pgAdmin4 coming afterwards, it has to be changed, and the changes should be easy.
To be discussed with upstream

**Comment by tigerfoot** [comment]
Issue opened at django-htmlmin.

I also discovered that flask-htmlmin exist (which would be more coherent for pgadmin4)

**Comment by Jenselme** [comment]
I don't think that we can do much more here. If this is still a real problem, reopen and we'll try to switch to another html minifier.
